"""Generated retrieval hooks for v6 core_rules.md.

The resident core is extracted before detailed packages and parameter
families exist. This post-finalize helper appends a compact, deterministic
hook section once the runtime index is known, so IC mode can see which
package/family IDs are available and which lookup tool should load them.
"""

from __future__ import annotations

import re
from typing import Any, Dict, Iterable, List, Tuple

HOOK_HEADING = "## On-Demand Rule Detail Index"
_HOOK_RE = re.compile(
    r"\n*## (?:Runtime Retrieval Hooks|On-Demand Rule Detail Index|运行时规则检索索引|按需规则细节索引)\n.*?(?=\n## |\Z)",
    re.DOTALL,
)


def strip_core_retrieval_hooks(core_rules: str) -> str:
    """Remove the generated hook section from a core_rules markdown string."""
    text = str(core_rules or "")
    return _HOOK_RE.sub("", text).strip()


def apply_core_retrieval_hooks(
    core_rules: str,
    *,
    manifest: Dict[str, Any],
    produced_family_results: List[Dict[str, Any]] | None = None,
    output_language: str | None = None,
) -> Tuple[str, Dict[str, int]]:
    """Return core_rules with the generated retrieval hook section refreshed."""
    base = strip_core_retrieval_hooks(core_rules)
    hook = build_core_retrieval_hooks(
        manifest=manifest,
        produced_family_results=produced_family_results or [],
        output_language=output_language,
    )
    stats = {
        "packages": len([p for p in (manifest.get("detailed_rule_packages") or []) if isinstance(p, dict)]),
        "families": len([f for f in (manifest.get("parameter_families") or []) if isinstance(f, dict)]),
    }
    if not base or not hook:
        return base, stats
    return f"{base}\n\n{hook}".strip(), stats


def build_core_retrieval_hooks(
    *,
    manifest: Dict[str, Any],
    produced_family_results: List[Dict[str, Any]],
    output_language: str | None = None,
) -> str:
    """Build the compact hook section appended to core_rules.md."""
    packages = [
        item for item in (manifest.get("detailed_rule_packages") or [])
        if isinstance(item, dict) and str(item.get("package_id") or "").strip()
    ]
    families = [
        item for item in (manifest.get("parameter_families") or [])
        if isinstance(item, dict) and str(item.get("family_id") or "").strip()
    ]
    if not packages and not families:
        return ""

    family_samples = _family_samples_by_id(produced_family_results)
    lang = _language(output_language)
    if lang == "zh":
        lines = [
            "## 按需规则细节索引",
            "",
            "本节由 v6 finalize 阶段生成。它不是额外规则，而是 core_rules.md 对冗长细节的按需检索入口。core_rules.md 是主运行手册，应足以流畅运行大多数游戏；只有当当前回合需要被压缩/拆出的情景规则、长例外链、表驱动内容或精确条目数值时，才按下面的 ID 调用检索工具。",
            "",
            "- 规则包：使用 `lookup_situational_rule`，参数为精确 `package_id`。",
            "- 参数族：使用 `lookup_list_entries`，参数为精确 `family_id` 和条目名称。",
            "- 优先依据 core_rules.md 裁决；只有 core 中的简述不足以决定结果时，才在叙事前检索相关细节。",
        ]
        if packages:
            lines += ["", "### 规则包钩子"]
            lines.extend(_format_package_lines(packages, zh=True))
        if families:
            lines += ["", "### 参数族钩子"]
            lines.extend(_format_family_lines(families, family_samples, zh=True))
        return "\n".join(lines).strip()

    lines = [
        HOOK_HEADING,
        "",
        "This section is generated by v6 finalize. It is not additional rules text; it is the on-demand detail index for material that was intentionally split out because it is too long, table-driven, exception-heavy, or entry-specific. core_rules.md remains the primary runtime manual and should be enough to run most play smoothly; use this index only when the current turn needs details that the core summarizes rather than fully embeds.",
        "",
        "- Rule packages: call `lookup_situational_rule` with the exact `package_id`.",
        "- Parameter families: call `lookup_list_entries` with the exact `family_id` plus entry name.",
        "- Prefer adjudicating from core_rules.md first; retrieve before narrating only when the summarized hook points to details that affect the outcome.",
    ]
    if packages:
        lines += ["", "### Rule Package Hooks"]
        lines.extend(_format_package_lines(packages, zh=False))
    if families:
        lines += ["", "### Parameter Family Hooks"]
        lines.extend(_format_family_lines(families, family_samples, zh=False))
    return "\n".join(lines).strip()


def _language(output_language: str | None) -> str:
    raw = str(output_language or "").strip().lower()
    return "zh" if raw in {"chinese", "zh", "zh-cn", "zh_cn", "中文"} else "en"


def _format_package_lines(packages: Iterable[Dict[str, Any]], *, zh: bool) -> List[str]:
    lines: List[str] = []
    for item in packages:
        package_id = str(item.get("package_id") or "").strip()
        title = str(item.get("title") or package_id).strip()
        load_when = _join_short(item.get("load_when"), max_chars=170)
        contains = _join_short(item.get("contains"), max_chars=130)
        summary = _short(str(item.get("summary") or ""), 150)
        details = [part for part in (load_when, contains, summary) if part]
        body = " | ".join(details) if details else (
            "load when this subsystem needs exact procedure"
            if not zh else "当该子系统需要精确流程时加载"
        )
        if zh:
            lines.append(
                f"- `{package_id}` ({title}): 调用 `lookup_situational_rule({{\"key\":\"{package_id}\"}})`；{body}"
            )
        else:
            lines.append(
                f"- `{package_id}` ({title}): use `lookup_situational_rule({{\"key\":\"{package_id}\"}})`; {body}"
            )
    return lines


def _format_family_lines(
    families: Iterable[Dict[str, Any]],
    samples_by_id: Dict[str, List[str]],
    *,
    zh: bool,
) -> List[str]:
    lines: List[str] = []
    for item in families:
        family_id = str(item.get("family_id") or "").strip()
        title = str(item.get("title") or family_id).strip()
        entry_definition = _short(str(item.get("entry_definition") or ""), 120)
        fields = _join_short(item.get("family_specific_fields"), max_chars=100)
        samples = ", ".join(samples_by_id.get(family_id, [])[:8])
        details = [part for part in (entry_definition, f"fields: {fields}" if fields else "", f"samples: {samples}" if samples else "") if part]
        body = " | ".join(details) if details else (
            "lookup exact named entries when their values matter"
            if not zh else "当条目的精确数值或限制影响结果时查询"
        )
        if zh:
            lines.append(
                f"- `{family_id}` ({title}): 调用 `lookup_list_entries({{\"queries\":[{{\"slug\":\"{family_id}\",\"name\":\"<entry name>\"}}]}})`；{body}"
            )
        else:
            lines.append(
                f"- `{family_id}` ({title}): use `lookup_list_entries({{\"queries\":[{{\"slug\":\"{family_id}\",\"name\":\"<entry name>\"}}]}})`; {body}"
            )
    return lines


def _family_samples_by_id(results: Iterable[Dict[str, Any]]) -> Dict[str, List[str]]:
    out: Dict[str, List[str]] = {}
    for result in results or []:
        if not isinstance(result, dict):
            continue
        family_id = str(result.get("family_id") or "").strip()
        if not family_id:
            continue
        names = _sample_entry_names(result.get("json"))
        if names:
            out[family_id] = names
    return out


def _sample_entry_names(value: Any, *, limit: int = 8) -> List[str]:
    entries = _entries_from_json(value)
    names: List[str] = []
    seen = set()
    for idx, entry in enumerate(entries):
        if isinstance(entry, dict):
            raw = (
                entry.get("name")
                or entry.get("title")
                or entry.get("label")
                or entry.get("id")
                or entry.get("key")
                or entry.get("slug")
            )
        else:
            raw = entry
        name = str(raw or "").strip()
        if not name:
            name = f"entry_{idx + 1}"
        if name in seen:
            continue
        seen.add(name)
        names.append(_short(name, 48))
        if len(names) >= limit:
            break
    return names


def _entries_from_json(value: Any) -> List[Any]:
    if isinstance(value, list):
        return value
    if isinstance(value, dict):
        for key in ("entries", "items", "options", "tables", "rows", "values"):
            nested = value.get(key)
            if isinstance(nested, list):
                return nested
        for nested in value.values():
            if isinstance(nested, list) and nested and all(isinstance(item, dict) for item in nested):
                return nested
    return []


def _join_short(value: Any, *, max_chars: int) -> str:
    if isinstance(value, list):
        text = ", ".join(str(item).strip() for item in value if str(item).strip())
    elif isinstance(value, dict):
        text = ", ".join(f"{k}: {v}" for k, v in value.items())
    else:
        text = str(value or "").strip()
    return _short(text, max_chars)


def _short(text: str, max_chars: int) -> str:
    compact = re.sub(r"\s+", " ", str(text or "")).strip()
    if len(compact) <= max_chars:
        return compact
    return compact[: max(max_chars - 1, 0)].rstrip() + "..."
